# Policyscope tutorial (короткая версия)

Цель: взять логи политики **A** и оценить качество новой политики **B** универсальными функциями, где имена колонок задаются аргументами.

> Важно: Bootstrap CI считается через единый API (`OPEEvaluator` / `estimate_value_with_ci`) и не является отдельным OPE-эстиматором.
> Это inference-обёртка для построения доверительных интервалов вокруг point-estimate (например, DR).

> В текущем репозитории CI реализованы через percentile bootstrap (row/cluster) и парный bootstrap для `(V_A, V_B, Delta)`.
> Другие подходы (например, BCa, Wald/IF, high-confidence bounds) описаны в `docs/ope_methods_math_guide_ru.md`.

> Новый универсальный интерфейс: `estimator_with_bootstrap_ci(df, estimator_fn, ...)` — можно строить CI для любого estimator_fn, не только для DR.

> Новый единый слой CI: `estimate_value_with_ci(df, policyB, method=...)` для встроенных OPE-эстиматоров.
> Используйте единый API: `OPEEvaluator(...).evaluate(method)` или `estimate_value_with_ci(..., method=...)`.

In [1]:
import sys
from pathlib import Path

repo_root = Path.cwd().resolve().parent if Path.cwd().name == "examples" else Path.cwd().resolve()
sys.path.insert(0, str(repo_root / "src"))

import numpy as np
import pandas as pd
from IPython.display import display

from policyscope.synthetic import SynthConfig, SyntheticRecommenderEnv
from policyscope.policies import make_policy
from policyscope.report import analyze_logs, decision_summary
from policyscope.estimators import (
    train_pi_hat,
    pi_hat_predict,
    train_mu_hat,
    prepare_piB_taken,
    take_action_probabilities,
    replay_value,
    ips_value,
    snips_value,
    dm_value,
    dr_value,
    sndr_value,
    switch_dr_value,
)

from policyscope.evaluator import OPEEvaluator
from policyscope.ci import estimate_value_with_ci


from policyscope.data import BanditSchema, LoggedBanditDataset

## 1) Генерируем пример и добавляем `a_B`

In [2]:
cfg = SynthConfig(n_users=1500, seed=42)
env = SyntheticRecommenderEnv(cfg)
X = env.sample_users()

policyA = make_policy("epsilon_greedy", seed=1, epsilon=0.15)
policyB = make_policy("softmax", seed=2, tau=0.7)

logs = env.simulate_logs_A(policyA, X)
logs["a_B"] = policyB.action_argmax(X)

feature_cols = ["loyal", "age", "risk", "income"]
action_col = "a_A"
target_col = "accept"

logs[feature_cols + [action_col, "a_B", target_col]].head(10)

   loyal  age      risk        income  a_A  a_B  accept
0      0   58  0.533906  42504.836685    1    1       0
1      1   52  0.771861  33375.544407    1    1       1
2      0   66  0.378868  16465.519421    1    1       0
3      0   67  0.587519  36489.365579    1    1       0
4      1   54  0.966203  20946.300727    1    1       1
5      0   37  0.521980  15257.204837    0    1       0
6      0   49  0.909798  38887.831289    1    1       0
7      0   40  0.793673  46348.382414    3    1       1
8      1   50  0.058719  47256.666884    0    0       1
9      1   60  0.429099  48222.710126    0    1       1

## 1.0) Валидация data contract для логов

Перед расчётами OPE валидируем структуру logged bandit данных через `BanditSchema` и `LoggedBanditDataset`.

In [3]:
schema = BanditSchema(
    action_col=action_col,
    reward_col=target_col,
    feature_cols=feature_cols,
    cluster_col="user_id",
)
logged = LoggedBanditDataset(df=logs, schema=schema)

print("Validated rows:", len(logged.df))
display(logged.features.head(5))

Validated rows: 1500

   loyal  age      risk        income
0      0   58  0.533906  42504.836685
1      1   52  0.771861  33375.544407
2      0   66  0.378868  16465.519421
3      0   67  0.587519  36489.365579
4      1   54  0.966203  20946.300727

## 1.1) Ground-truth до OPE (только на синтетике)

Считаем истинные (oracle) значения для `V_A`, `V_B` и `Δ` на синтетике. После этого **не используем синтезатор** в расчётах OPE, чтобы не допустить data leakage.

In [4]:
oracle_vA = env.oracle_value(policyA, X, metric=target_col, n_mc=200)
oracle_vB = env.oracle_value(policyB, X, metric=target_col, n_mc=200)
oracle_df = pd.DataFrame({
    "metric": [target_col],
    "V_A_oracle": [oracle_vA],
    "V_B_oracle": [oracle_vB],
    "Delta_oracle": [oracle_vB - oracle_vA],
})
display(oracle_df)

# ВАЖНО: синтезатор дальше в OPE-оценках не используем.
env = None
X = None

   metric  V_A_oracle  V_B_oracle  Delta_oracle
0  accept    0.528963     0.50113     -0.027833

## 2) Проверка данных (универсально по именам колонок)

In [5]:
print(analyze_logs(
    logs,
    policyB,
    action_a_col="a_A",
    action_b_col="a_B",
    user_id_col="user_id",
    targets=("accept", "cltv"),
    feature_cols=feature_cols,
))

Проверка входных данных для off-policy оценки:

- Колонки user_id и a_A найдены.

- Найден столбец a_B; пересечение с a_A: 53.6%.

- Replay: политика B совпадает с A в 53.6% случаев.

- IPS/SNIPS: propensities не найдены. Необходимо добавить колонку с π_A(a|x) или обучить модель пропенсити.

- DM: доступны признаки ['loyal', 'age', 'risk', 'income'], ок.

- DR: пропенсити отсутствуют, но можно применить DM; метод DR будет смещён, если модель неточна.

Проверка входных данных для off-policy оценки:
- Колонки user_id и a_A найдены.
- Найден столбец a_B; пересечение с a_A: 53.6%.
- Replay: политика B совпадает с A в 53.6% случаев.
- IPS/SNIPS: propensities не найдены. Необходимо добавить колонку с π_A(a|x) или обучить модель пропенсити.
- DM: доступны признаки ['loyal', 'age', 'risk', 'income'], ок.
- DR: пропенсити отсутствуют, но можно применить DM; метод DR будет смещён, если модель неточна.

## 3) Компактный расчёт всех OPE-оценок

In [6]:
piB_taken = prepare_piB_taken(logs, policyB, action_col=action_col)

pi_model = train_pi_hat(logs, feature_cols=feature_cols, action_col=action_col)
pA_all = pi_hat_predict(pi_model, logs)
pA_taken = take_action_probabilities(pA_all, logs[action_col].values, action_space=pi_model.classes_)

mu = train_mu_hat(logs, target=target_col, feature_cols=feature_cols, action_col=action_col)

v_replay = replay_value(logs, logs["a_B"].values, target=target_col, action_col=action_col)
v_ips, ess_ips, clip_ips = ips_value(logs, piB_taken, pA_taken, target=target_col, action_col=action_col)
v_snips, ess_snips, clip_snips = snips_value(logs, piB_taken, pA_taken, target=target_col, action_col=action_col)
v_dm = dm_value(logs, policyB, mu, target=target_col)
v_dr, ess_dr, clip_dr = dr_value(logs, policyB, mu, pA_taken, target=target_col, action_col=action_col)
v_sndr, ess_sndr, clip_sndr = sndr_value(logs, policyB, mu, pA_taken, target=target_col, action_col=action_col)
v_switch, ess_switch, clip_switch = switch_dr_value(logs, policyB, mu, pA_taken, tau=20.0, target=target_col, action_col=action_col)

v_a = float(logs[target_col].mean())
method_rows = [
    {"Метод": "On-policy A", "V_B": v_a, "Delta к A": 0.0, "ESS": np.nan, "Доля clip/switch": np.nan},
    {"Метод": "Replay", "V_B": v_replay, "Delta к A": v_replay - v_a, "ESS": np.nan, "Доля clip/switch": np.nan},
    {"Метод": "IPS", "V_B": v_ips, "Delta к A": v_ips - v_a, "ESS": ess_ips, "Доля clip/switch": clip_ips},
    {"Метод": "SNIPS", "V_B": v_snips, "Delta к A": v_snips - v_a, "ESS": ess_snips, "Доля clip/switch": clip_snips},
    {"Метод": "DM", "V_B": v_dm, "Delta к A": v_dm - v_a, "ESS": np.nan, "Доля clip/switch": np.nan},
    {"Метод": "DR", "V_B": v_dr, "Delta к A": v_dr - v_a, "ESS": ess_dr, "Доля clip/switch": clip_dr},
    {"Метод": "SNDR", "V_B": v_sndr, "Delta к A": v_sndr - v_a, "ESS": ess_sndr, "Доля clip/switch": clip_sndr},
    {"Метод": "Switch-DR (tau=20)", "V_B": v_switch, "Delta к A": v_switch - v_a, "ESS": ess_switch, "Доля clip/switch": clip_switch},
]

comparison_df = pd.DataFrame(method_rows)
comparison_df.style.format({"V_B": "{:.4f}", "Delta к A": "{:+.4f}", "ESS": "{:.1f}", "Доля clip/switch": "{:.2%}"})

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 804 из 1500

[Replay] Оценённое значение метрики: 0.5075

[IPS] Начинаем оценку IPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

## 3.1) Унифицированный вызов через объект `OPEEvaluator`

Ниже один и тот же интерфейс для всех эстиматоров: переключаем только имя метода. CI считается по умолчанию.

In [7]:
evaluator = OPEEvaluator(
    logs,
    policyB,
    target=target_col,
    feature_cols=feature_cols,
    action_col=action_col,
    cluster_col="user_id",
    n_boot=30,
    weight_clip=20.0,
)

methods = ["ips", "snips", "dm", "dr", "sndr", "switch_dr"]
obj_rows = [evaluator.evaluate(m) for m in methods]
display(pd.DataFrame(obj_rows)[["estimator", "V_A", "V_B", "Delta", "V_B_CI", "Delta_CI"]])

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

,estimator,V_A,V_B,Delta,V_B_CI,Delta_CI
0,ips,0.518667,0.559052,0.040385,"(0.48171136080232824, 0.5951242058838352)","(-0.04759865117469708, 0.07783122507383895)"
1,snips,0.518667,0.514983,-0.003684,"(0.4641935819930148, 0.5449143253224658)","(-0.056796998485161544, 0.031206039091902955)"
2,dm,0.518667,0.494396,-0.024271,"(0.4697214315136772, 0.5154190786548842)","(-0.03802890997187793, -0.013529290351846975)"
3,dr,0.518667,0.502238,-0.016429,"(0.4441224031647932, 0.5372764677133788)","(-0.07706871739592618, 0.021700927994128833)"
4,sndr,0.518667,0.501620,-0.017047,"(0.4476887565074596, 0.5355098598742425)","(-0.07411084477538234, 0.01776836608061231)"
5,switch_dr,0.518667,0.488357,-0.030310,"(0.4386177148620148, 0.5292308957939488)","(-0.08125941424572253, 0.009156794552684882)"

## 4) CI для всех методов через единый API

In [8]:
# CI для всех методов через единый high-level API
method_map = [
    ("On-policy A", "on_policy"),
    ("Replay", "replay"),
    ("IPS", "ips"),
    ("SNIPS", "snips"),
    ("DM", "dm"),
    ("DR", "dr"),
    ("SNDR", "sndr"),
    ("Switch-DR (tau=20)", "switch_dr"),
]

all_ci_reports = []
for method_label, method_name in method_map:
    report = evaluator.evaluate(method_name)
    all_ci_reports.append({
        "Метод": method_label,
        "V_A": report["V_A"],
        "V_A_CI": f"[{report['V_A_CI'][0]:.4f}; {report['V_A_CI'][1]:.4f}]",
        "V_B": report["V_B"],
        "V_B_CI": f"[{report['V_B_CI'][0]:.4f}; {report['V_B_CI'][1]:.4f}]",
        "Delta к A": report["Delta"],
        "Delta_CI": f"[{report['Delta_CI'][0]:+.4f}; {report['Delta_CI'][1]:+.4f}]",
        "n_boot": report["n_boot"],
    })

all_ci_df = pd.DataFrame(all_ci_reports)
print(decision_summary(evaluator.evaluate("dr"), metric_name=target_col, business_threshold=0.0))

# Итоговая таблица: point-estimate + CI для каждого метода
comparison_with_ci = comparison_df.merge(
    all_ci_df[["Метод", "V_B_CI", "Delta_CI"]],
    on="Метод",
    how="left",
)
comparison_with_ci["Источник"] = "bootstrap CI (paired)"

display(comparison_with_ci.style.format({"V_B": "{:.4f}", "Delta к A": "{:+.4f}", "ESS": "{:.1f}", "Доля clip/switch": "{:.2%}"}))
display(all_ci_df.style.format({"V_A": "{:.4f}", "V_B": "{:.4f}", "Delta к A": "{:+.4f}"}))

# Для удобства: отдельный DR-результат тем же единым API
evaluator.evaluate("dr")

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 804 из 1500

[Replay] Оценённое значение метрики: 0.5075

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 804 из 1500

[Replay] Оценённое значение метрики: 0.5075

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 786 из 1500

[Replay] Оценённое значение метрики: 0.5267

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 825 из 1500

[Replay] Оценённое значение метрики: 0.4885

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 806 из 1500

[Replay] Оценённое значение метрики: 0.4938

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 792 из 1500

[Replay] Оценённое значение метрики: 0.5088

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 783 из 1500

[Replay] Оценённое значение метрики: 0.5160

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 767 из 1500

[Replay] Оценённое значение метрики: 0.5020

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 791 из 1500

[Replay] Оценённое значение метрики: 0.4968

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 794 из 1500

[Replay] Оценённое значение метрики: 0.5479

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 796 из 1500

[Replay] Оценённое значение метрики: 0.4874

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 825 из 1500

[Replay] Оценённое значение метрики: 0.4994

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 804 из 1500

[Replay] Оценённое значение метрики: 0.4789

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 823 из 1500

[Replay] Оценённое значение метрики: 0.5261

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 817 из 1500

[Replay] Оценённое значение метрики: 0.5129

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 813 из 1500

[Replay] Оценённое значение метрики: 0.4834

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 805 из 1500

[Replay] Оценённое значение метрики: 0.4994

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 824 из 1500

[Replay] Оценённое значение метрики: 0.5291

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 823 из 1500

[Replay] Оценённое значение метрики: 0.5103

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 806 из 1500

[Replay] Оценённое значение метрики: 0.5062

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 803 из 1500

[Replay] Оценённое значение метрики: 0.5193

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 802 из 1500

[Replay] Оценённое значение метрики: 0.5062

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 817 из 1500

[Replay] Оценённое значение метрики: 0.4663

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 794 из 1500

[Replay] Оценённое значение метрики: 0.4950

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 780 из 1500

[Replay] Оценённое значение метрики: 0.4949

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 802 из 1500

[Replay] Оценённое значение метрики: 0.4925

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 776 из 1500

[Replay] Оценённое значение метрики: 0.5258

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 821 из 1500

[Replay] Оценённое значение метрики: 0.4811

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 793 из 1500

[Replay] Оценённое значение метрики: 0.4968

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 836 из 1500

[Replay] Оценённое значение метрики: 0.5060

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 820 из 1500

[Replay] Оценённое значение метрики: 0.5256

[Replay] Начинаем оценку Replay для новой политики…

[Replay] Совпадающих действий: 774 из 1500

[Replay] Оценённое значение метрики: 0.5258

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[IPS] Начинаем оценку IPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

[SNIPS] Начинаем оценку SNIPS для новой политики…

Метрика: accept
V(A) = 0.518667 (95% CI: 0.491733 .. 0.540033)
V(B) = 0.502238 (95% CI: 0.444122 .. 0.537276)
Delta (B−A) = -0.016429 (95% CI: -0.077069 .. 0.021701)
Решение: статистически значимого отличия не обнаружено или эффект слишком мал.

{'estimator': 'dr',
 'V_A': 0.5186666666666667,
 'V_B': 0.5022380276025321,
 'Delta': -0.01642863906413461,
 'V_A_CI': (0.4917333333333333, 0.5400333333333334),
 'V_B_CI': (0.4441224031647932, 0.5372764677133788),
 'Delta_CI': (-0.07706871739592618, 0.021700927994128833),
 'p_value': None,
 'is_significant': False,
 'significance_rule': 'delta_ci_excludes_zero',
 'n_boot': 30,
 'alpha': 0.05,
 'inference_method': 'paired_percentile_bootstrap',
 'inference_warnings': ['p_value_not_reported_use_ci_rule']}

## 5) Как перенести на свой датасет

1. Замените `logs` на свой DataFrame.
2. Передайте свои имена колонок в `feature_cols`, `action_col`, `target`.
3. Если у вас нет `user_id`, используйте `cluster_col=None` в `OPEEvaluator(..., cluster_col=None)` или `estimate_value_with_ci(..., cluster_col=None)`.
4. Для унифицированного вызова всех методов используйте `OPEEvaluator` и меняйте только имя эстиматора в `evaluate("...")`.
5. Колонка `a_B` не обязательна для OPE, но полезна для диагностики и визуального контроля.